version: '3.6'
x-logging: &logging
  logging:
    options:
      max-size: '10m'
      max-file: '3'
services:
  mongo:
    <<: *logging
    image: mongo
    command: --wiredTigerEngineConfigString="cache_size=256M"
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27017:27017
    restart: always
    deploy:
      resources:
        limits:
          memory: 1g
  mongo-express:
    <<: *logging
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD}
      - NODE_OPTIONS=--max-old-space-size=200
    restart: always
    deploy:
      resources:
        limits:
          memory: 200m
volumes:
  mongo:
